name: client_mobile
description: Farmer-Vet mobile client (starter)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.0.5
  http: ^1.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2 

  # ✅ THE FIX: These lines now have the correct indentation.
  # They must be aligned with the other packages.
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/